version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    depends_on:
      - pythonservice

  pythonservice:
    build: ./pythonservice
    container_name: python_service
    env_file: ./backend/.env
    command: ["uvicorn", "clip_service:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    depends_on:
      - backend
